name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-ubuntu:
    name: Test on ubuntu x86 and arm64
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      
      - name: Build debug
        run: cargo build --verbose

      - name: Build release
        run: cargo build --release --verbose
        
      - name: Run tests debug 
        run: cargo test --verbose

      - name: Run tests release
        run: cargo test --release --verbose

  test-windows:
    name: Test on Windows x86_64
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            %USERPROFILE%\.cargo\registry
            %USERPROFILE%\.cargo\git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build debug
        run: cargo build --verbose

      - name: Build release
        run: cargo build --release --verbose

      - name: Run tests debug
        run: cargo test --verbose

      - name: Run tests release
        run: cargo test --release --verbose
